### ISSUE TITLE
OSC to MMC

### ISSUE THREAD

**Issue by 80prozent** [fred-dev/OSC_MIDI_OSC#2]
I am playing around with using this app to talk from OSC to cubase.

The supported commands work well. Great tool.

It would be even better if it would allow me to translate OSC to MMC commands, so that i can control the playback of cubase to.

Any plans to add that feature ?

**Comment by fred-dev** [comment]
Seems like a good idea, I'll try get around to it soon.

**Comment by 80prozent** [comment]
Great. 
Thanks for your answer. 
For now i can do all i really need by cubase "step 1 bar forward / step 1 bar backward" commands, controlled via normal midi, but that is restricted to move the playhead only on full bars, not to any position in between. 
For my purpose i think its enough, and i can seek through cubase just by firing multiple of those commands in short time.
A mmc conrol would be much better tho...

**Comment by fred-dev** [comment]
I have implemented the MMC feature, I could only test with protools, as far as I can tell it is working fine.

**Comment by 80prozent** [comment]
Hey. 
Thats great news. Thanks
I am pretty much stuck on other projects right now, but i hope i will find time soon to test if it will work for my usecase. Will let you know once i have tested !
