### ISSUE TITLE
Sysex

### ISSUE THREAD

**Issue by AlexFundorin** [fred-dev/OSC_MIDI_OSC#4]
Hi. Is there sysex support within this app? 
Can't check myself, since it's crashing every time I start it.
https://i.imgur.com/YiNBP5x.png

**Comment by fred-dev** [comment]
No, I did not implement sysex, I will take a look at the error (it is a strange one, can you give me your windows version) and sysex implementation soon.

**Comment by AlexFundorin** [comment]
This is my version - https://i.imgur.com/3OQNfJA.png

**Comment by fred-dev** [comment]
Ok, I don't have access to that build and don't know if I can support an
outdated preview version. Is this a real licence?

**Comment by AlexFundorin** [comment]
It is licensed. The reason why I'm not updating is because I had issues with preview versions, so I've rolled back to the previous build and set the update setting to only update to the major release.

I'm also interested, if it's possible to use scripting logic (if/then/else/switch) to convert midi<>osc data?

UPD. Upgraded to creators fall. Still crashes.

**Comment by fred-dev** [comment]
I'm currently implementing some changes and going through errors. The crash may have appeared if you did not have any midi ports present. If you have time to test this hypothesis let me know. I am pushing some changes that will give the app it's own midi ports to stop this (but it will change the setup a little bit).
