### ISSUE TITLE
Remap commands

### ISSUE THREAD

**Issue by drummerclint** [fred-dev/OSC_MIDI_OSC#5]
Is it possible to map a separate osc command from a midi command (for example, midi note 20 sends osc /pb/1/go).

Thanks!

**Comment by fred-dev** [comment]
There is as yet no functionality to change the osc or note output. The osc
output is a description of the midi input. A few people have asked for
script ability but I have not had time to implement it.

**Comment by drummerclint** [comment]
That's fair!  Thank you!
