### ISSUE TITLE
MacOs 10.13.5 (17F77)

### ISSUE THREAD

**Issue by JulesMichael** [fred-dev/OSC_MIDI_OSC#6]
Hello, 
I try to use this with macOs 10.13.5 (17F77) but i can't. (Or maybe I don't how this work)

**Comment by fred-dev** [comment]
I cannot support this on 10.13 at the moment.

**Comment by JulesMichael** [comment]
Okey, I found a solution. To run correctly the app I need to go to the executable file in the content of the package.

**Comment by fred-dev** [comment]
So it runs ok on osx 12.13

**Comment by hofno** [comment]
> Okey, I found a solution. To run correctly the app I need to go to the executable file in the content of the package.

doesnt do much for me.. im on 10.13.6. did you do anything else besides running it from contents?

**Comment by JulesMichael** [comment]
> > Okey, I found a solution. To run correctly the app I need to go to the executable file in the content of the package.
> 
> doesnt do much for me.. im on 10.13.6. did you do anything else besides running it from contents?

Hm no. Can you show what's in your terminal ?

**Comment by hofno** [comment]
![midi_osc_midi screenshot](https://user-images.githubusercontent.com/24904174/56956569-7e23dc80-6b3c-11e9-84c3-106056bc1c31.png)

thats the screenshot

**Comment by JulesMichael** [comment]
Do you have midi devices connected to your computer ?

**Comment by hofno** [comment]
no i dont
im trying to translate OSC coming from wekinator into MIDI that ABleton live could digest. i am not really attempting to connect any hardware at all. is that what you re doing with it?

**Comment by JulesMichael** [comment]
Check the “Audio midi setup”  app and create a virtual midi port (window > show midi studio, double click on “Virtual midi” and create a new port)
And launch the app again
