### ISSUE TITLE
50% GPU usage on run?

### ISSUE THREAD

**Issue by cwpenhale** [fred-dev/OSC_MIDI_OSC#7]
![2019-03-04 21_01_58-task manager](https://user-images.githubusercontent.com/5437215/53780266-dcc43580-3ec0-11e9-8e78-d539abaa2f31.png)

Any thoughts on this one? What can I provide to help with troubleshooting? Any steps on building myself to see if its a platform thing?

**Comment by cwpenhale** [comment]
![fixed](https://user-images.githubusercontent.com/5437215/53782173-5cee9900-3ec9-11e9-831c-7e83c6494cc7.png)

Capping the frame rate fixed the issue for me. Thanks for the code!

**Comment by fred-dev** [comment]
I'm working on a few updates, I'll be making new releases soon. I'll merge your pr shortly, thanks. 

Also can you tell me the OS version you are using?

**Comment by fred-dev** [comment]
This seems fixed in the new version, let me know.
